version: "3.9"

services:
  redis:
    image: "repository.umisen.com/external/redis:latest"
    container_name: redis
    restart: unless-stopped
    volumes:
      - .data/redis:/data
    ports:
      - "6379:6379"

  pgsql:
    image: "repository.umisen.com/external/postgres:latest"
    container_name: pgsql
    restart: unless-stopped
    environment:
      POSTGRES_USER: ult
      POSTGRES_PASSWORD: ult@sonar
      POSTGRES_DB: ult
      PGDATA: /var/lib/postgresql/data
    volumes:
      - .data/pgsql:/var/lib/postgresql
    ports:
      - "5432:5432"

  es:
    image: "repository.umisen.com/external/es:latest"
    container_name: es
    restart: unless-stopped
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - discovery.type=single-node
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    ports:
      - 9200:9200

  kibana:
    image: "repository.umisen.com/external/kibana:latest"
    container_name: kibana
    restart: unless-stopped
    environment:
      ELASTICSEARCH_HOSTS: http://elk_es:9200
      I18N_LOCALE: zh-CN
    ports:
      - 5601:5601